sudo: false
language: node_js
node_js:
- '0.12'
before_install:
- npm install -g npm
- currentfolder=${PWD##*/}
- if [ "$currentfolder" != 'generator-ag-library' ]; then cd .. && eval "mv $currentfolder
  generator-ag-library" && cd generator-ag-library; fi
deploy:
  provider: npm
  edge: true
  email: hostmaster+npm@appgyver.com
  api_key:
    secure: h4cYAUKed7hJt7s68MCILqQ208ufpKkSHvgg+HT9NRT7itUdFkq5FMItUeDTw0IIeVhH3i+k9P3wR7HP6rWurUA+dDy5rN52RJvqRr0sZQEEQ2NldWHT7643sx5oNZ6hMqKyGCSo7Fd/PwVqFBTYrdUW9OeoYa/+CdnELSHb/D0=
  on:
    tags: true
    all_branches: true
    repo: AppGyver/generator-ag-library
