sudo: false
language: node_js
node_js:
- '0.12'
before_install:
- npm install -g npm
- currentfolder=${PWD##*/}
- if [ "$currentfolder" != 'generator-ag-library' ]; then cd .. && eval "mv $currentfolder
  generator-ag-library" && cd generator-ag-library; fi
deploy:
  provider: npm
  edge: true
  email: hostmaster+npm@appgyver.com
  api_key:
    secure: Wg5LOi6EZkfHywExtphvhsKRT0UcuddO/099byWvesXZu/0c3322Lc95q+DDguYQkxklafjWVq8Kppisk0ulJT2Uswv+9qmlkuGgCSrnAGV9naYG87odaannnlWJJ3Uf7xG79Tbep8gWEYeGeObhp4vexfEOV8W5F6TBKtHH0WU=
  on:
    tags: true
    all_branches: true
    repo: AppGyver/generator-ag-library
