sudo: false
language: node_js
node_js:
- '0.10'
before_install:
- npm install -g npm
- currentfolder=${PWD##*/}
- if [ "$currentfolder" != 'generator-ag-library' ]; then cd .. && eval "mv $currentfolder
  generator-ag-library" && cd generator-ag-library; fi
deploy:
  provider: npm
  email: hostmaster+npm@appgyver.com
  api_key:
    secure: GhWFVzqb2WNUHMOmlBEXqYGD8dlzo3s+8nzwWh7PRPTkfNHoaUUBFJfwrudZsrszU9s7pcWEWH50Jc59x/+ens7owO9GtPsyBqL92m2b6AJb6EciZh/rYjh7CGwVO696GbQiyfW75MWrgOuA6IMZnvmj3dIIH/VoPHpX1vcYPE4=
  on:
    tags: true
    all_branches: true
    repo: AppGyver/generator-ag-library
